#!/bin/bash
# Morning Briefing Generator
# Synthesizes overnight activity into actionable summary

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VAULT_PATH="${VAULT_PATH:-$HOME/obsidian/openclaw}"
DATE=$(date +%Y-%m-%d)
YESTERDAY=$(date -v-1d +%Y-%m-%d 2>/dev/null || date -d "yesterday" +%Y-%m-%d)

echo "=== Morning Briefing Generator ==="
echo "Generating briefing for: $DATE"

# Ensure directories exist
mkdir -p "$VAULT_PATH/01-daily"
mkdir -p "$VAULT_PATH/05-sessions"

# Count sources checked (from logs if available)
SOURCES_CHECKED=$(find "$VAULT_PATH/03-patterns" -name "*.md" -mtime -1 2>/dev/null | wc -l || echo "0")

# Count new transcripts
NEW_TRANSCRIPTS=$(find "$VAULT_PATH" -name "*.md" -mtime -1 2>/dev/null | wc -l || echo "0")

# Count patterns extracted
PATTERNS_EXTRACTED=$(grep -l "Thinking Architecture" "$VAULT_PATH/03-patterns"/*.md 2>/dev/null | wc -l || echo "0")

# Count build proposals
BUILD_PROPOSALS=$(grep -l "Status: Proposed" "$VAULT_PATH/03-patterns"/*.md 2>/dev/null | wc -l || echo "0")

# Generate briefing
BRIEFING_FILE="$VAULT_PATH/01-daily/$DATE-morning-briefing.md"

cat > "$BRIEFING_FILE" << EOF
# Morning Briefing — $DATE

*Generated: $(date '+%H:%M')*

## Overnight Activity Summary

| Metric | Count |
|--------|-------|
| Sources monitored | $SOURCES_CHECKED |
| New transcripts processed | $NEW_TRANSCRIPTS |
| Patterns extracted | $PATTERNS_EXTRACTED |
| Build proposals pending | $BUILD_PROPOSALS |

## System Status
- Self-improvement loop: ✅ ACTIVE
- Pre-compaction persistence: ✅ CONFIGURED
- Auto-scheduling: ⏳ RUNNING (via cron)

## Pending Actions
$(if [ "$BUILD_PROPOSALS" -gt 0 ]; then
    echo "### Build Proposals Awaiting Approval"
    for file in "$VAULT_PATH/03-patterns"/*.md; do
        if [ -f "$file" ] && grep -q "Status: Proposed" "$file" 2>/dev/null; then
            TITLE=$(grep "^#" "$file" | head -1 | sed 's/^# //')
            echo "- **$TITLE** — [[$(basename "$file" .md)|View]]"
        fi
    done
    echo ""
    echo "Reply 'build [name]' to approve, or 'skip [name]' to discard."
else
    echo "No pending build proposals."
fi)

## Today's Self-Improvement Task
$(if [ -f "$VAULT_PATH/self-improvement/daily-tasks/$DATE-task.md" ]; then
    grep "^## Task" "$VAULT_PATH/self-improvement/daily-tasks/$DATE-task.md" | head -1
else
    echo "No task generated yet. Run: bash scripts/self-improvement-loop.sh --daily-surprise"
fi)

## One-Line Focus
$(if [ "$BUILD_PROPOSALS" -gt 0 ]; then
    echo "Review and approve build proposals."
elif [ "$PATTERNS_EXTRACTED" -gt 0 ]; then
    echo "Explore extracted patterns in 03-patterns/."
else
    echo "System running smoothly. Next auto-run at $(date -v+12H +%H:%M 2>/dev/null || date -d '+12 hours' +%H:%M)."
fi)

---
*Auto-generated by OpenClaw 10x System*
EOF

echo ""
echo "✓ Briefing generated: $BRIEFING_FILE"
echo ""
echo "Summary:"
echo "  Sources: $SOURCES_CHECKED"
echo "  Transcripts: $NEW_TRANSCRIPTS"
echo "  Patterns: $PATTERNS_EXTRACTED"
echo "  Proposals: $BUILD_PROPOSALS"

# Telegram notification (if configured)
if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then
    curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
        -d "chat_id=$TELEGRAM_CHAT_ID" \
        -d "text=📊 Morning Briefing — $DATE%0A%0ASources: $SOURCES_CHECKED | Patterns: $PATTERNS_EXTRACTED | Proposals: $BUILD_PROPOSALS%0A%0ASee vault: 01-daily/$DATE-morning-briefing.md" \
        -d "parse_mode=HTML" > /dev/null 2>&1 || true
fi
