#!/usr/bin/env bash
# Generate daily handoff from radar queue
# Follows OUTPUT_STANDARD.md format

set -euo pipefail

RADAR_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="${OPENCLAW_WORKSPACE:-$(cd "$RADAR_DIR/.." && pwd)}"
QUEUE_DIR="$RADAR_DIR/queue"
OUTPUT="$WORKSPACE_ROOT/memory/$(date +%Y-%m-%d)-radar-handoff.md"
mkdir -p "$(dirname "$OUTPUT")"

count_lines() {
  local file="$1"
  if [ -f "$file" ]; then
    wc -l < "$file" | tr -d ' '
  else
    echo 0
  fi
}

cat > "$OUTPUT" << EOF
# Radar Handoff — $(date +%Y-%m-%d)
**Scan Period:** Last 24 hours  
**Channels:** GitHub, HackerNews, YouTube

---

## What I Found

EOF

# High priority signals
if [ -f "$QUEUE_DIR/urgent-alerts.jsonl" ] && [ -s "$QUEUE_DIR/urgent-alerts.jsonl" ]; then
    echo "### 🚨 Urgent Opportunities" >> "$OUTPUT"
    tail -5 "$QUEUE_DIR/urgent-alerts.jsonl" | while read line; do
        echo "- $(echo $line | jq -r '[.source, .title] | @tsv')" >> "$OUTPUT"
    done
    echo "" >> "$OUTPUT"
fi

# Asset packs queued
ASSETS=$(ls -1t "$QUEUE_DIR"/asset-*.json 2>/dev/null | head -3)
if [ -n "$ASSETS" ]; then
    echo "### 📦 Asset Packs Queued" >> "$OUTPUT"
    for f in $ASSETS; do
        echo "- $(basename $f .json)" >> "$OUTPUT"
    done
    echo "" >> "$OUTPUT"
fi

# Content ideas
if [ -f "$QUEUE_DIR/content-ideas.jsonl" ] && [ -s "$QUEUE_DIR/content-ideas.jsonl" ]; then
    echo "### ✍️  Content Ideas" >> "$OUTPUT"
    tail -3 "$QUEUE_DIR/content-ideas.jsonl" | while read line; do
        echo "- $(echo $line | jq -r '.title // "New idea"')" >> "$OUTPUT"
    done
    echo "" >> "$OUTPUT"
fi

cat >> "$OUTPUT" << EOF

---

## Tonight's Top 3

1. 
2. 
3. 

## Queue Status

| Type | Count |
|------|-------|
| Urgent Alerts | $(count_lines "$QUEUE_DIR/urgent-alerts.jsonl") |
| Asset Packs | $(ls -1 "$QUEUE_DIR"/asset-*.json 2>/dev/null | wc -l) |
| Content Ideas | $(count_lines "$QUEUE_DIR/content-ideas.jsonl") |
| Research | $(count_lines "$QUEUE_DIR/research-queue.jsonl") |

---

*Generated by radar-system at $(date -Iseconds)*
EOF

echo "Handoff written to: $OUTPUT"
